import http from 'node:http';import crypto from 'node:crypto';import {pathToFileURL} from 'node:url';
export const equal=(a,b)=>{const x=Buffer.from(a||''),y=Buffer.from(b||'');return x.length===y.length&&crypto.timingSafeEqual(x,y);};
export function verifyTwilio(url,p,s,key){return !!s&&!!key&&equal(crypto.createHmac('sha1',key).update(url+Object.keys(p).sort().map(k=>k+p[k]).join('')).digest('base64'),s);}
export function verifyCal(raw,s,key){return !!s&&!!key&&equal(crypto.createHmac('sha256',key).update(raw).digest('hex'),s);}
export function verifyResend(raw,h,key,now=Date.now()){if(!key||!h['svix-id']||!h['svix-timestamp']||!h['svix-signature'])return false;const ts=Number(h['svix-timestamp']);if(!Number.isFinite(ts)||Math.abs(now/1000-ts)>300)return false;const sig=crypto.createHmac('sha256',Buffer.from(key.replace(/^whsec_/,''),'base64')).update(h['svix-id']+'.'+ts+'.'+raw.toString()).digest('base64');return h['svix-signature'].split(' ').some(s=>s.startsWith('v1,')&&equal(s.slice(3),sig));}
export const optout=s=>/\b(stop|unsubscribe|remove me|do not contact|don't contact|no more messages|no thanks|not interested)\b/i.test(s||'');
export async function handle(req,res,env=process.env){const send=(code,body,type='application/json')=>{res.writeHead(code,{'content-type':type,'cache-control':'no-store'});res.end(typeof body==='string'?body:JSON.stringify(body));};if(req.method==='GET'&&req.url==='/health')return send(200,{ok:true});if(req.method!=='POST'||!['/callbacks/twilio','/callbacks/cal','/callbacks/resend'].includes(req.url))return send(404,{error:'Not found'});let raw=Buffer.alloc(0);try{for await(const x of req){raw=Buffer.concat([raw,x]);if(raw.length>512000)return send(413,{error:'Payload too large'});}let event,endpoint='provider-events';if(req.url==='/callbacks/twilio'){const form=new URLSearchParams(raw.toString());if([...form.keys()].length!==new Set(form.keys()).size)return send(400,{error:'Duplicate parameters'});const p=Object.fromEntries(form);if(!verifyTwilio(String(env.PUBLIC_GATEWAY_URL||'').replace(/\/$/,'')+req.url,p,req.headers['x-twilio-signature'],env.TWILIO_AUTH_TOKEN))return send(401,{error:'Invalid signature'});if(p.Body!==undefined){endpoint='follow-up';event={event_id:'sms:'+p.MessageSid,operation:optout(p.Body)?'optout':'reply',contact:{phone:p.From,consent:false}};}else event={provider:'twilio',event_id:'sms-status:'+p.MessageSid+':'+p.MessageStatus,type:p.MessageStatus,provider_id:p.MessageSid};}
 else if(req.url==='/callbacks/cal'){if(!verifyCal(raw,req.headers['x-cal-signature-256'],env.CAL_WEBHOOK_SECRET))return send(401,{error:'Invalid signature'});const p=JSON.parse(raw);event={provider:'cal',event_id:'cal:'+crypto.createHash('sha256').update(raw).digest('hex'),type:p.triggerEvent,payload:p.payload};}
 else{if(!verifyResend(raw,req.headers,env.RESEND_WEBHOOK_SECRET))return send(401,{error:'Invalid signature'});const p=JSON.parse(raw);if(p.type==='email.received'){endpoint='follow-up';let text=p.data.subject||'';if(env.RESEND_API_KEY&&p.data.email_id){const r=await fetch('https://api.resend.com/emails/receiving/'+encodeURIComponent(p.data.email_id),{headers:{authorization:'Bearer '+env.RESEND_API_KEY},signal:AbortSignal.timeout(5000)});if(r.ok){const b=await r.json();text+='\n'+String(b.text||'').slice(0,30000);}}const from=String(p.data.from||'');event={event_id:'mail:'+req.headers['svix-id'],operation:optout(text)?'optout':'reply',contact:{email:(from.match(/<([^<>]+)>/)?.[1]||from).trim().toLowerCase(),consent:false}};}else event={provider:'resend',event_id:req.headers['svix-id'],type:p.type,provider_id:p.data?.email_id};}
 if(!env.GROWNIC_WEBHOOK_KEY||!env.N8N_INTERNAL_BASE)return send(503,{error:'Gateway not configured'});const response=await fetch(env.N8N_INTERNAL_BASE.replace(/\/$/,'')+'/webhook/grownic/'+endpoint+'/v1',{method:'POST',headers:{'content-type':'application/json','x-grownic-key':env.GROWNIC_WEBHOOK_KEY},body:JSON.stringify(event),signal:AbortSignal.timeout(12000)});if(!response.ok)return send(502,{error:'Event not accepted; provider should retry'});if(req.url==='/callbacks/twilio')return send(200,'<?xml version="1.0"?><Response/>','text/xml');return send(200,{ok:true});}catch{return send(503,{error:'Event processing unavailable; retry later'});}}
if(import.meta.url===pathToFileURL(process.argv[1]||'').href){const s=http.createServer((r,p)=>handle(r,p));s.requestTimeout=15000;s.headersTimeout=10000;s.listen(Number(process.env.PORT||8080),'0.0.0.0');}
