import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
const root=path.resolve(import.meta.dirname,'..'),read=f=>fs.readFileSync(path.join(root,f),'utf8');
const pure=['common','agents','delivery'].map(x=>read('src/'+x+'.js')).join('\n');
const id=s=>crypto.createHash('sha256').update('grownic-v1/'+s).digest('hex').slice(0,16);
const creds=(type,name)=>({[type]:{id:'grc-'+name,name:'Grownic '+name}});
export const agents=[['01','speed-to-lead','Speed to Lead'],['02','lead-generation','Lead Generation'],['03','quote','Quote'],['04','voice','Voice Receptionist'],['05','follow-up','Follow Up'],['06','appointment','Appointment Setting'],['07','recruitment','Recruitment Review'],['08','content','Content Repurposing'],['09','marketing','Marketing Experiments'],['10','support','Customer Support']];
const workflows=[];
function wf(key,title){return {id:id(key),name:'Grownic | '+title,active:false,nodes:[],connections:{},settings:{executionOrder:'v1',timezone:'UTC',saveDataSuccessExecution:'none',saveDataErrorExecution:'all',executionTimeout:120,errorWorkflow:id('90-error-monitor')},pinData:{},versionId:crypto.randomUUID(),meta:{templateCredsSetupCompleted:false},tags:[]};}
function node(w,name,type,v,p,xy,extra={}){w.nodes.push({id:id(w.id+'/'+name),name,type:'n8n-nodes-base.'+type,typeVersion:v,position:xy,parameters:p,...extra});return name;}
function code(w,n,js,xy,each=false){return node(w,n,'code',2,{mode:each?'runOnceForEachItem':'runOnceForAllItems',jsCode:pure+'\n'+js},xy);}
function pg(w,n,q,args,xy){return node(w,n,'postgres',2.7,{operation:'executeQuery',query:q,options:{queryReplacement:args,queryBatching:'independently'}},xy,{credentials:creds('postgres','Postgres')});}
function edge(w,a,b,out=0){w.connections[a]??={main:[]};w.connections[a].main[out]??=[];w.connections[a].main[out].push({node:b,type:'main',index:0});}
function iff(w,n,exp,xy){return node(w,n,'if',2.3,{conditions:{options:{caseSensitive:true,leftValue:'',typeValidation:'strict',version:2},conditions:[{id:id(n),leftValue:exp,rightValue:true,operator:{type:'boolean',operation:'true',singleValue:true}}],combinator:'and'},options:{}},xy);}
function hook(w,n,end,xy,method='POST',admin=false){return node(w,n,'webhook',2.1,{httpMethod:method,path:'grownic/'+end+'/v1',authentication:admin?'basicAuth':'headerAuth',responseMode:'responseNode',options:{}},xy,{webhookId:id(end+method),credentials:creds(admin?'httpBasicAuth':'httpHeaderAuth',admin?'Review Login':'Webhook Key')});}
function respond(w,n,body,xy,html=false,status='={{ $json.http_code || 200 }}'){return node(w,n,'respondToWebhook',1.5,{respondWith:html?'text':'json',responseBody:body,options:{responseCode:status,responseHeaders:{entries:[{name:'Content-Type',value:html?'text/html; charset=utf-8':'application/json'},{name:'Cache-Control',value:'no-store'}]}}},xy);}
function http(w,n,provider,url,method,body,xy,opts={}){const sms=provider==='Twilio';const p={method,url,authentication:'genericCredentialType',genericAuthType:sms?'httpBasicAuth':'httpHeaderAuth',sendHeaders:true,headerParameters:{parameters:[]},options:{timeout:opts.timeout||45000,response:{response:{fullResponse:true,neverError:true,responseFormat:'json'}},redirect:{redirect:{followRedirects:false}}}};if(body){Object.assign(p,{sendBody:true,contentType:sms?'form-urlencoded':'json',specifyBody:sms?'keypair':'json'});if(sms)p.bodyParameters={parameters:['To','Body','MessagingServiceSid'].map(name=>({name,value:'={{ $json.http.body.'+name+' }}'}))};else p.jsonBody=body;}if(opts.version)p.headerParameters.parameters.push({name:'cal-api-version',value:opts.version});if(provider==='Resend')p.headerParameters.parameters.push({name:'Idempotency-Key',value:'={{ "grownic-" + $json.id }}'});return node(w,n,'httpRequest',4.5,p,xy,{credentials:creds(sms?'httpBasicAuth':'httpHeaderAuth',provider),onError:'continueRegularOutput',retryOnFail:false});}
function save(w,file){fs.mkdirSync(path.join(root,'workflows'),{recursive:true});fs.writeFileSync(path.join(root,'workflows',file+'.json'),JSON.stringify(w,null,2)+'\n');workflows.push({w,file:'workflows/'+file+'.json'});}
for(const [num,slug,title]of agents){const w=wf(slug,num+' '+title);
 hook(w,'Receive Request',slug,[0,200]);
 code(w,'Normalize Request',`try {const r=${slug==='voice'?'G.voiceRequest($input.first().json)':`G.normalize('${slug}',$input.first().json)`};${slug==='follow-up'?"G.assert(['run','enroll','reply','optout','booked','bounce'].includes(r.operation),'Unsupported operation');":''}return [{json:{valid:true,request:r}}];}catch(e){return [{json:{valid:false,http_code:400,error:e.message}}];}`,[230,200]);
 iff(w,'Valid Input?','={{ $json.valid === true }}',[460,200]);respond(w,'Input Error','={{ {error:$json.error} }}',[690,540]);
 pg(w,'Claim Event','SELECT grownic.begin_event($1::jsonb) AS context;','={{ [JSON.stringify($json.request)] }}',[690,200]);iff(w,'New Event?','={{ $json.context.proceed === true }}',[920,200]);respond(w,'Existing Event','={{ $json.context.result }}',[1150,540],false,'={{ $json.context.http_code }}');
 code(w,'Prepare Context','const c=$json.context;try{G.prepare(c);}catch(e){c.flow_error=e.message;}return [{json:c}];',[1150,200]);iff(w,'Read Live Context?','={{ !!$json.remote && $json.cfg.mode === "live" && !$json.flow_error }}',[1380,200]);
 const provider=slug==='lead-generation'?'Tavily':slug==='marketing'?'Meta':'Cal';http(w,'Read Upstream',provider,'={{ $json.remote.url }}','={{ $json.remote.method }}',slug==='lead-generation'?'={{ JSON.stringify($json.remote.body) }}':null,[1610,40],{version:['voice','appointment'].includes(slug)?'={{ $json.cfg.cal_slots_version }}':'',timeout:slug==='voice'?7000:45000});
 code(w,'Use Live Context',"const c=$('Prepare Context').first().json;try{G.withExternal(c,$json);}catch(e){c.flow_error=e.message;}return [{json:c}];",[1840,40]);
 code(w,'Use Test or Local Context',"const c=$json;try{if(!c.flow_error)G.withExternal(c,c.cfg.mode==='test'?c.request.test_data?.upstream||{}:{});}catch(e){c.flow_error=e.message;}return [{json:c}];",[1840,360]);
 iff(w,'Call Model?','={{ !!$json.ai_request && $json.cfg.mode === "live" && !$json.flow_error }}',[2070,200]);http(w,'Structured AI','OpenAI','https://api.openai.com/v1/responses','POST','={{ JSON.stringify($json.ai_request) }}',[2300,40]);
 const finish=`try{return [{json:G.finish(c,ai)}];}catch(e){const p=G.plan(c);p.result={status:'needs_human',reason:e.message};G.record(p,'task',c.request.agent+':'+c.request.event_id,p.result);return [{json:p}];}`;
 code(w,'Build AI Plan',"const c=$('Call Model?').first().json,ai=G.parseAI($json);"+finish,[2530,40]);
 code(w,'Build Rules or Test Plan',"const c=$json,ai=c.cfg.mode==='test'&&c.ai_request?{ok:!!c.request.test_data?.ai,data:c.request.test_data?.ai,error:'Provide test_data.ai in test mode'}:null;"+finish,[2530,360]);
 pg(w,'Commit Plan','SELECT grownic.commit_plan($1::jsonb) AS result;','={{ [JSON.stringify($json)] }}',[2760,200]);respond(w,'Return Result','={{ $json.result }}',[2990,200]);
 for(const[a,b,o]of [['Receive Request','Normalize Request'],['Normalize Request','Valid Input?'],['Valid Input?','Claim Event'],['Valid Input?','Input Error',1],['Claim Event','New Event?'],['New Event?','Prepare Context'],['New Event?','Existing Event',1],['Prepare Context','Read Live Context?'],['Read Live Context?','Read Upstream'],['Read Live Context?','Use Test or Local Context',1],['Read Upstream','Use Live Context'],['Use Live Context','Call Model?'],['Use Test or Local Context','Call Model?'],['Call Model?','Structured AI'],['Call Model?','Build Rules or Test Plan',1],['Structured AI','Build AI Plan'],['Build AI Plan','Commit Plan'],['Build Rules or Test Plan','Commit Plan']])edge(w,a,b,o);
 if(slug==='voice'){
 pg(w,'Claim Voice Booking',"SELECT coalesce(jsonb_agg(x),'[]') AS actions FROM grownic.claim_actions(1,'voice',$1) x;",'={{ [$("Normalize Request").first().json.request.event_id] }}',[2990,200]);
 code(w,'Voice Action',"return [{json:$json.actions[0]||{none:true}}];",[3220,200]);iff(w,'Has Booking?','={{ !$json.none }}',[3450,200]);
 pg(w,'Recheck Voice Permission','SELECT grownic.preflight_action($1::bigint,$2::text) AS action;','={{ [$json.id,$json.lease_token] }}',[3680,40]);code(w,'Use Voice Action','return [{json:$json.action}];',[3910,40]);iff(w,'Voice Allowed?','={{ $json.send === true }}',[4140,40]);
 code(w,'Build Voice Delivery',"try{return [{json:G.deliveryRequest($json)}];}catch(e){return [{json:{...$json,build_error:e.message}}];}",[4370,40]);iff(w,'Voice Request Valid?','={{ !$json.build_error }}',[4600,40]);
 http(w,'Book with Cal','Cal','={{ $json.http.url }}','POST','={{ JSON.stringify($json.http.body) }}',[4830,40],{version:'={{ $json.http.version }}',timeout:8000});code(w,'Voice Provider Outcome',"return [{json:G.deliveryOutcome($('Build Voice Delivery').first().json,$json)}];",[5060,40]);
 code(w,'Voice Failure',"return [{json:{id:$json.id,lease_token:$json.lease_token,status:'failed',error:$json.build_error}}];",[4830,330]);pg(w,'Record Voice Booking','SELECT grownic.finish_action($1::jsonb) AS result;','={{ [JSON.stringify($json)] }}',[5290,40]);
 pg(w,'Read Voice Results',"SELECT result,coalesce((SELECT jsonb_agg(jsonb_build_object('tool_call_id',metadata->>'tool_call_id','status',status,'uid',provider_id)) FROM grownic.outbox WHERE agent='voice' AND event_id=$1),'[]') AS bookings FROM grownic.events WHERE agent='voice' AND event_id=$1;",'={{ [$("Normalize Request").first().json.request.event_id] }}',[5520,200]);
 code(w,'Format Voice Response',"const decode=v=>{if(G.object(v))return v;if(typeof v==='string')try{return JSON.parse(v)}catch{}return {};},row=$json,committed=decode($('Commit Plan').first().json.result),stored=decode(row.result),results=Array.isArray(stored.results)?stored.results:(Array.isArray(committed.results)?committed.results:[]),rawBookings=typeof row.bookings==='string'?decode(row.bookings):row.bookings,bookings=Array.isArray(rawBookings)?rawBookings:[];for(const t of results){const b=bookings.find(x=>x.tool_call_id===t.toolCallId);if(b)t.result=JSON.stringify(b.status==='accepted'?{status:'confirmed',booking_uid:b.uid}:{status:b.status,information:'Booking not confirmed. Offer callback.'});}return [{json:{results}}];",[5750,200]);
 pg(w,'Store Voice Response',"UPDATE grownic.events SET result=$2::jsonb WHERE agent='voice' AND event_id=$1 RETURNING result;",'={{ [$("Normalize Request").first().json.request.event_id,JSON.stringify($json)] }}',[5980,200]);w.nodes.find(x=>x.name==='Return Result').position=[6210,200];
 for(const[a,b,o]of [['Commit Plan','Claim Voice Booking'],['Claim Voice Booking','Voice Action'],['Voice Action','Has Booking?'],['Has Booking?','Recheck Voice Permission'],['Has Booking?','Read Voice Results',1],['Recheck Voice Permission','Use Voice Action'],['Use Voice Action','Voice Allowed?'],['Voice Allowed?','Build Voice Delivery'],['Voice Allowed?','Read Voice Results',1],['Build Voice Delivery','Voice Request Valid?'],['Voice Request Valid?','Book with Cal'],['Voice Request Valid?','Voice Failure',1],['Book with Cal','Voice Provider Outcome'],['Voice Provider Outcome','Record Voice Booking'],['Voice Failure','Record Voice Booking'],['Record Voice Booking','Read Voice Results'],['Read Voice Results','Format Voice Response'],['Format Voice Response','Store Voice Response'],['Store Voice Response','Return Result']])edge(w,a,b,o);
 }else edge(w,'Commit Plan','Return Result');
 node(w,'Setup Notes','stickyNote',1,{content:`## ${num} ${title}\nImport inactive. Configure PostgreSQL and named credentials.\nTEST is the default. Fixtures make no paid API calls.\nRead README.md and docs/DEPLOY.md.`,height:200,width:550},[0,-100]);save(w,num+'-'+slug);
}
{
const w=wf('80-delivery','80 Delivery Worker');node(w,'Every 10 Seconds','scheduleTrigger',1.3,{rule:{interval:[{field:'seconds',secondsInterval:10}]}},[0,0]);node(w,'Manual Run','manualTrigger',1,{},[0,200]);pg(w,'Recover and Reconcile','SELECT grownic.recover_leases(),grownic.reconcile_provider_events();','={{ [] }}',[230,0]);pg(w,'Claim One Action','SELECT x AS action FROM grownic.claim_actions(1) x;','={{ [] }}',[460,0]);code(w,'Unpack Action','return $input.all().filter(x=>x.json.action).map(x=>({json:x.json.action}));',[690,0]);pg(w,'Recheck Permission','SELECT grownic.preflight_action($1::bigint,$2::text) AS action;','={{ [$json.id,$json.lease_token] }}',[920,0]);code(w,'Use Current Action','return [{json:$json.action}];',[1150,0]);iff(w,'Allowed?','={{ $json.send === true }}',[1380,0]);code(w,'Build Delivery',"try{return [{json:G.deliveryRequest($json)}];}catch(e){return [{json:{...$json,build_error:e.message}}];}",[1610,0]);iff(w,'Valid Delivery?','={{ !$json.build_error }}',[1840,0]);code(w,'Validation Failure',"return [{json:{id:$json.id,lease_token:$json.lease_token,status:'failed',error:$json.build_error}}];",[2070,520]);
for(const[a,b]of [['Every 10 Seconds','Recover and Reconcile'],['Manual Run','Recover and Reconcile'],['Recover and Reconcile','Claim One Action'],['Claim One Action','Unpack Action'],['Unpack Action','Recheck Permission'],['Recheck Permission','Use Current Action'],['Use Current Action','Allowed?'],['Allowed?','Build Delivery'],['Build Delivery','Valid Delivery?']])edge(w,a,b);edge(w,'Valid Delivery?','Validation Failure',1);
let previous='Valid Delivery?';for(const[i,[kind,provider]]of[['email','Resend'],['sms','Twilio'],['hubspot_contact','HubSpot'],['cal_','Cal'],['publora_post','Publora'],['meta_','Meta']].entries()){const n='Is '+provider+'?';iff(w,n,kind.endsWith('_')?'={{ $json.kind.startsWith("'+kind+'") }}':'={{ $json.kind === "'+kind+'" }}',[2070+i*240,0]);edge(w,previous,n,previous==='Valid Delivery?'?0:1);previous=n;http(w,'Send '+provider,provider,'={{ $json.http.url }}','POST','={{ JSON.stringify($json.http.body) }}',[2070+i*240,280],{version:kind==='cal_'?'={{ $json.http.version }}':''});edge(w,n,'Send '+provider);edge(w,'Send '+provider,'Classify Outcome');}
code(w,'Classify Outcome',"return [{json:G.deliveryOutcome($('Build Delivery').first().json,$json)}];",[3600,280]);pg(w,'Record Outcome','SELECT grownic.finish_action($1::jsonb) AS result;','={{ [JSON.stringify($json)] }}',[3830,280]);pg(w,'Prepare Paused Ad','SELECT grownic.approved_meta_ad($1::bigint);','={{ [$json.result.id] }}',[4060,280]);edge(w,'Validation Failure','Record Outcome');edge(w,'Classify Outcome','Record Outcome');edge(w,'Record Outcome','Prepare Paused Ad');save(w,'80-delivery-worker');
}
{
const w=wf('81-scheduler','81 Follow Up and Reminder Scheduler');node(w,'Every Minute','scheduleTrigger',1.3,{rule:{interval:[{field:'minutes',minutesInterval:1}]}},[0,0]);node(w,'Manual Run','manualTrigger',1,{},[0,200]);pg(w,'Load Due Work','SELECT x AS request FROM grownic.due_work() x;','={{ [] }}',[230,0]);pg(w,'Claim Scheduled Event','SELECT grownic.begin_event($1::jsonb) AS context;','={{ [JSON.stringify($json.request)] }}',[460,0]);iff(w,'New Event?','={{ $json.context.proceed === true }}',[690,0]);code(w,'Prepare Message','return {json:G.followupPlan($json.context)};',[920,0],true);pg(w,'Commit Message','SELECT grownic.commit_plan($1::jsonb) AS result;','={{ [JSON.stringify($json)] }}',[1150,0]);for(const[a,b]of [['Every Minute','Load Due Work'],['Manual Run','Load Due Work'],['Load Due Work','Claim Scheduled Event'],['Claim Scheduled Event','New Event?'],['New Event?','Prepare Message'],['Prepare Message','Commit Message']])edge(w,a,b);save(w,'81-followup-scheduler');
}
{
const w=wf('82-review','82 Owner Review Console');hook(w,'Open Review','review',[0,0],'GET',true);pg(w,'Load Queue',"SELECT (SELECT config->>'public_n8n_url' FROM grownic.settings WHERE id) AS base,coalesce(jsonb_agg(t),'[]') AS actions FROM(SELECT * FROM grownic.outbox WHERE status IN('needs_review','unknown','failed') ORDER BY id DESC LIMIT 100)t;",'={{ [] }}',[230,0]);code(w,'Render Page','return [{json:{html:G.renderReview($json.actions,$json.base)}}];',[460,0]);respond(w,'Review Page','={{ $json.html }}',[690,0],true);
hook(w,'Review Decision','review',[0,350],'POST',true);code(w,'Validate Decision',"const p=$json.body;G.assert(G.object(p)&&/^[0-9]+$/.test(String(p.action_id))&&['approve','reject'].includes(p.decision)&&/^[a-f0-9]{64}$/.test(p.expected_hash),'Invalid approval form');return [{json:p}];",[230,350]);pg(w,'Apply Decision','SELECT grownic.review_action($1::jsonb) AS result;','={{ [JSON.stringify($json)] }}',[460,350]);respond(w,'Decision Saved','={{ $json.result }}',[690,350]);
hook(w,'Read Test State','health',[0,700],'GET',true);pg(w,'Read State',"SELECT config->>'mode' AS mode,(config->>'outbound_enabled')::boolean AS outbound_enabled FROM grownic.settings WHERE id;",'={{ [] }}',[230,700]);respond(w,'State Response','={{ $json }}',[460,700]);
for(const[a,b]of [['Open Review','Load Queue'],['Load Queue','Render Page'],['Render Page','Review Page'],['Review Decision','Validate Decision'],['Validate Decision','Apply Decision'],['Apply Decision','Decision Saved'],['Read Test State','Read State'],['Read State','State Response']])edge(w,a,b);save(w,'82-review-console');
}
{
const w=wf('83-provider','83 Verified Provider Events');hook(w,'Verified Event','provider-events',[0,0]);code(w,'Validate Event',"const p=$json.body;G.assert(G.object(p)&&['cal','twilio','resend'].includes(p.provider)&&G.text(p.event_id),'Verified gateway event required');return [{json:p}];",[230,0]);pg(w,'Apply Event','SELECT grownic.provider_event($1::jsonb) AS result;','={{ [JSON.stringify($json)] }}',[460,0]);respond(w,'Event Saved','={{ $json.result }}',[690,0]);edge(w,'Verified Event','Validate Event');edge(w,'Validate Event','Apply Event');edge(w,'Apply Event','Event Saved');save(w,'83-provider-events');
}
{
const w=wf('84-knowledge','84 Approved Knowledge Ingest');hook(w,'Owner Knowledge Upload','knowledge',[0,0],'POST',true);code(w,'Validate Documents',"const docs=$json.body.documents;G.assert(Array.isArray(docs)&&docs.length>0&&docs.length<=100,'Send 1-100 approved FAQ documents');return docs.map((d,i)=>{G.assert(G.text(d.id)&&G.text(d.title)&&G.text(d.question)&&G.text(d.answer,12000)&&G.host(d.source_url)&&d.approved===true,'Approved id/title/question/answer/HTTPS source required');if(d.expires_at)G.iso(d.expires_at);return {json:d,pairedItem:{item:0}};});",[230,0]);pg(w,'Store Answers',"INSERT INTO grownic.knowledge(id,title,question,answer,source_url,approved,expires_at) VALUES($1,$2,$3,$4,$5,true,$6::timestamptz) ON CONFLICT(id) DO UPDATE SET title=excluded.title,question=excluded.question,answer=excluded.answer,source_url=excluded.source_url,approved=true,expires_at=excluded.expires_at,updated_at=now() RETURNING id;",'={{ [$json.id,$json.title,$json.question,$json.answer,$json.source_url,$json.expires_at||null] }}',[460,0]);code(w,'Summary','return [{json:{stored_ids:$input.all().map(x=>x.json.id)}}];',[690,0]);respond(w,'Knowledge Saved','={{ $json }}',[920,0]);for(const[a,b]of [['Owner Knowledge Upload','Validate Documents'],['Validate Documents','Store Answers'],['Store Answers','Summary'],['Summary','Knowledge Saved']])edge(w,a,b);save(w,'84-knowledge-ingest');
}
{
const w=wf('90-error-monitor','90 Execution Error Monitor');delete w.settings.errorWorkflow;node(w,'Execution Failed','errorTrigger',1,{},[0,0]);pg(w,'Record Failure','INSERT INTO grownic.failures(workflow,execution_id,message) VALUES($1,$2,$3) RETURNING id;','={{ [$json.workflow?.name||"unknown",$json.execution?.id||"",($json.execution?.error?.message||$json.trigger?.error?.message||"Unknown error").slice(0,3000)] }}',[230,0]);edge(w,'Execution Failed','Record Failure');save(w,'90-error-monitor');
}
fs.writeFileSync(path.join(root,'all-workflows.json'),JSON.stringify(workflows.map(x=>x.w),null,2)+'\n');fs.writeFileSync(path.join(root,'manifest.json'),JSON.stringify({package:'Grownic 10-Agent Suite',version:'1.1.1',built:new Date().toISOString(),n8n_version:'2.38.7',workflows:workflows.map(x=>({file:x.file,id:x.w.id,name:x.w.name}))},null,2)+'\n');console.log('Built 10 agent workflows + 6 shared workflows');
