import fs from 'node:fs';import path from 'node:path';import {pathToFileURL} from 'node:url';
export function fixtures(now=Date.now()){
 const start=new Date(now+7*86400000).toISOString(),start2=new Date(now+7*86400000+3600000).toISOString(),contact=n=>({name:'Alex Demo',email:n+'@example.invalid',timezone:'America/New_York',consent:true,consent_source:'Synthetic fixture; no real recipient'}),upstream={status:'success',data:{[start.slice(0,10)]:[{start},{start:start2}]}};
 const source='Every service enquiry should have a named owner and a next action. Keeping the agreed scope alongside the quote makes the handoff easier to review.';
 return [
 {slug:'speed-to-lead',expect:'response_prepared',payload:{event_id:'demo-speed-1',service:'commercial cleaning',source:'Demo web form',contact:contact('speed')}},
 {slug:'lead-generation',expect:'ready_for_review',payload:{event_id:'demo-leads-1',query:'Synthetic fixture',test_data:{upstream:{results:[{url:'https://example.com/contact',raw_content:'Example Services provides building maintenance. Public business inbox: hello@example.com.'}]},ai:{leads:[{source_id:'0',company:'Example Services',company_quote:'Example Services',email:'hello@example.com',email_quote:'hello@example.com',description:'Building maintenance',fit_reason:'Service enquiries',fit_quote:'provides building maintenance'}]}}}},
 {slug:'quote',expect:'quote_prepared',payload:{event_id:'demo-quote-1',contact:contact('quote'),items:[{service_id:'cleaning',quantity:3},{service_id:'consultation',quantity:1}]}},
 {slug:'voice',expect:'voice_results',payload:{message:{type:'tool-calls',call:{id:'demo-call-1',customer:{number:'+12025550123'}},toolCallList:[{id:'services',name:'lookup_services',arguments:{}},{id:'slots',name:'check_availability',arguments:{}}]},test_data:{upstream}}},
 {slug:'follow-up',expect:'enrollment_requested',payload:{event_id:'demo-followup-1',operation:'enroll',contact:contact('followup'),service:'commercial cleaning',stage:'quoted',channel:'email'}},
 {slug:'appointment',expect:'slots_available',payload:{event_id:'demo-appointment-1',operation:'availability',contact:contact('appointment'),test_data:{upstream}}},
 {slug:'recruitment',expect:'human_review_required',payload:{event_id:'demo-recruitment-1',contact:contact('candidate'),resume_text:'I managed appointment schedules for a maintenance company and used spreadsheets for operational tracking.',test_data:{ai:{requirements:[{id:'scheduling',status:'evidenced',quote:'managed appointment schedules'},{id:'customer_service',status:'unclear',quote:''},{id:'spreadsheets',status:'evidenced',quote:'used spreadsheets for operational tracking'}],questions:['Please describe how you handled schedule changes.']}}}},
 {slug:'content',expect:'drafts_ready',payload:{event_id:'demo-content-1',source_text:source,source_url:'https://example.com/operations',test_data:{ai:{posts:[{platform:'linkedin',idea:'Ownership',source_quote:'a named owner and a next action',text:'Give every service enquiry a named owner and a next action. These two fields make a handoff easier to review.'},{platform:'x',idea:'Scope',source_quote:'Keeping the agreed scope alongside the quote',text:'Keep the agreed scope alongside the quote so the next person has the context.'},{platform:'instagram',idea:'Handoff',source_quote:'makes the handoff easier to review',text:'Clear ownership and visible scope make a handoff easier to review.'}]}}}},
 {slug:'marketing',expect:'experiments_for_review',payload:{event_id:'demo-marketing-1',approved_offer:'Book a service assessment. No guaranteed results or discounts.',test_data:{upstream:{data:[{id:'demo-ad-1',name:'Service assessment',creative:{body:'Book a service assessment'},insights:{data:[{impressions:'2000',clicks:'40',spend:'100',actions:[{action_type:'lead',value:'5'}]}]}}]},ai:{observations:['One synthetic ad is insufficient for a performance comparison.'],variants:[{headline:'Plan your next service visit',body:'Book a service assessment to discuss the work you need.',hypothesis:'Clear scope language may improve enquiry quality.',success_metric:'cost_per_lead',source_ad_ids:['demo-ad-1']},{headline:'Talk through your service needs',body:'Start with a service assessment.',hypothesis:'Shorter copy may improve response.',success_metric:'ctr',source_ad_ids:['demo-ad-1']},{headline:'Make the next step clear',body:'Book a service assessment and discuss your requirements.',hypothesis:'A clear next step may improve enquiries.',success_metric:'cost_per_lead',source_ad_ids:['demo-ad-1']}]}}}},
 {slug:'support',expect:'grounded_reply_prepared',payload:{event_id:'demo-support-1',question:'What are your opening hours?',contact:contact('support'),test_data:{ai:{intent:'public_faq',answer_ids:['demo-hours'],reason:'Question asks opening hours'}}}}
 ];
}
export const knowledge={documents:[{id:'demo-hours',title:'Opening hours',question:'What are your opening hours?',answer:'Our demo office is open Monday to Friday, 9am to 5pm, New York time.',source_url:'https://example.com/hours',approved:true}]};
if(import.meta.url===pathToFileURL(process.argv[1]).href){const dir=path.resolve(import.meta.dirname,'../fixtures');fs.mkdirSync(dir,{recursive:true});for(const[i,f]of fixtures().entries())fs.writeFileSync(path.join(dir,String(i+1).padStart(2,'0')+'-'+f.slug+'.json'),JSON.stringify(f.payload,null,2)+'\n');fs.writeFileSync(path.join(dir,'00-knowledge.json'),JSON.stringify(knowledge,null,2)+'\n');console.log('Wrote synthetic inputs for all ten agents. Regenerate for fresh calendar timestamps.');}
