G.deliveryRequest=a=>{const c=a.cfg,p=a.payload;G.assert(a.status==='sending'&&a.lease_token&&c.mode==='live'&&c.outbound_enabled===true,'Owned live delivery lease required');let url,version='';
 if(a.kind==='email'){G.assert(Array.isArray(p.to)&&p.to.length===1&&G.email(p.to[0])&&!G.testAddress(p.to[0]),'One real email required');G.assert(!/[\r\n]/.test(p.subject)&&a.contact?.email===p.to[0]&&a.contact.consent,'Email must match current consenting contact');url='https://api.resend.com/emails';}
 else if(a.kind==='sms'){G.assert(G.phone(p.To)&&p.To===a.contact?.phone&&a.contact.consent,'SMS must match consenting contact');G.assert(/^AC[a-fA-F0-9]{32}$/.test(c.twilio_account_sid)&&/^MG[a-fA-F0-9]{32}$/.test(p.MessagingServiceSid),'Valid Twilio account and service required');url='https://api.twilio.com/2010-04-01/Accounts/'+c.twilio_account_sid+'/Messages.json';}
 else if(a.kind==='hubspot_contact')url='https://api.hubapi.com/crm/v3/objects/contacts/batch/upsert';
 else if(a.kind.startsWith('cal_')){G.assert(Number.isInteger(c.cal_event_type_id)&&c.cal_event_type_id>0,'Real Cal event type required');url='https://api.cal.com/v2/bookings';version=c.cal_bookings_version;if(a.kind!=='cal_book'){G.assert(/^[A-Za-z0-9_-]+$/.test(a.metadata.booking_uid),'Invalid booking UID');url+='/'+encodeURIComponent(a.metadata.booking_uid)+(a.kind==='cal_cancel'?'/cancel':'/reschedule');}else G.assert(p.eventTypeId===c.cal_event_type_id,'Event type changed');if(p.start)G.assert(Date.parse(p.start)>Date.now(),'Booking time passed');}
 else if(a.kind==='publora_post'){G.assert(p.platforms.length===1&&p.platforms[0]===c.publora_connections.x&&!String(p.platforms[0]).startsWith('linkedin-'),'Only approved X connection enabled');url='https://api.publora.com/api/v1/create-post';}
 else if(a.kind.startsWith('meta_')){G.assert(/^act_\d+$/.test(c.meta_ad_account_id)&&/^v\d+\.0$/.test(c.meta_api_version),'Valid Meta account/version required');if(a.kind==='meta_ad')G.assert(p.status==='PAUSED'&&p.adset_id===c.meta_adset_id,'Ad must remain PAUSED in configured adset');url='https://graph.facebook.com/'+c.meta_api_version+'/'+c.meta_ad_account_id+(a.kind==='meta_ad'?'/ads':'/adcreatives');}else throw new Error('No delivery adapter');
 return {...a,http:{url,method:'POST',body:p,version}};
};
G.deliveryOutcome=(a,r)=>{const code=Number(r?.statusCode)||0,b=r?.body??r;let id='',status='unknown',error='Outcome unconfirmed; reconcile provider before retry';if(code>=200&&code<300){if(a.kind==='email')id=b.id;if(a.kind==='sms')id=b.sid;if(a.kind==='hubspot_contact')id=b.results?.[0]?.id;if(a.kind.startsWith('cal_'))id=b.data?.uid||(a.kind==='cal_cancel'&&b.status==='success'?a.metadata.booking_uid:'');if(a.kind==='publora_post')id=b.postGroupId;if(a.kind.startsWith('meta_'))id=b.id;}
 if(id){status='accepted';error=null;if(['cal_book','cal_reschedule'].includes(a.kind)&&String(b.data?.status).toLowerCase()!=='accepted'){status='unknown';error='Booking exists but is not confirmed; review provider status';}}
 else if(code===429&&a.attempts<5){status='ready';error='Rate limited; delayed retry';}else if(code>=400&&code<500){status='failed';error='Provider rejected request (HTTP '+code+')';}else if(a.kind==='email'&&a.attempts<5&&Date.now()-Date.parse(a.first_attempt_at)<23*3600000){status='ready';error='Retry with same Resend idempotency key';}
 return {id:a.id,lease_token:a.lease_token,status,provider_id:id?String(id):null,error,response:{http_status:code,provider_status:b?.data?.status||b?.status||null}};
};
G.renderReview=(rows,base)=>{const cards=rows.map(a=>'<article><small>#'+a.id+' · '+G.escape(a.agent)+' · '+G.escape(a.kind)+' · '+G.escape(a.status)+'</small><h2>'+G.escape(a.contact_key||'Internal review')+'</h2><pre>'+G.escape(JSON.stringify(a.payload,null,2))+'</pre>'+(a.status==='needs_review'?'<form method="POST" target="_top" action="'+G.escape(base.replace(/\/$/,'')+'/webhook/grownic/review/v1')+'"><input type="hidden" name="action_id" value="'+a.id+'"><input type="hidden" name="expected_hash" value="'+a.payload_hash+'"><label>Suggestion / comment<textarea name="comment" maxlength="4000"></textarea></label><button name="decision" value="approve">Approve exact action</button><button name="decision" value="reject">Reject</button></form>':'<p>'+G.escape(a.last_error||'Review provider record before retry')+'</p>')+'</article>').join('');return '<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Grownic review queue</title><style>body{font:16px system-ui;background:#0b1119;color:#eaf0f7;max-width:1050px;margin:40px auto;padding:0 20px}article{background:#141f2d;border:1px solid #304154;padding:24px;border-radius:12px;margin:20px 0}small{color:#eac27a}pre{white-space:pre-wrap;overflow-wrap:anywhere;font:14px/1.5 monospace}textarea{display:block;width:95%;padding:12px;margin:12px 0}button{background:#eac27a;border:0;padding:12px 20px;margin:8px;cursor:pointer;border-radius:5px}</style><h1>Grownic · Review queue</h1><p>Approval applies to the exact recipient and payload shown. In test mode, approval simulates the action.</p>'+cards+'</html>';};
